In [1]:
from source.inputters.corpus import KnowledgeCorpus
corpus = KnowledgeCorpus('./data/', 'demo', max_len=500, max_vocab_size=30000, share_vocab=True)
corpus.load()
valid_raw = corpus.read_data('./data/demo.dev', data_type='valid')
valid_data = corpus.build_examples(valid_raw)

from source.inputters.dataset import Dataset
data = Dataset(valid_data)
loader = data.create_batches(5)
for input in loader:
    input = input
    break

Loading prepared vocab from ./data/demo_30000.vocab.pt ...
Vocabulary size of fields: SRC-30004 TGT-30004 CUE-30004
Loading prepared data from ./data/demo_30000.data.pt ...
Number of examples: TRAIN-89901 VALID-9054 TEST-9054
Read 9054 VALID examples (0 filtered)


100%|████████████████████████████████████████████████████████████████████████████| 9054/9054 [00:00<00:00, 9814.92it/s]


In [2]:
enc_inputs = input
# y(t-1)
dec_inputs = input.tgt[0][:, :-1], input.tgt[1] - 1
# y(t)
target = input.tgt[0][:, 1:]

In [3]:
enc_inputs.src

(tensor([[   2,   30,    4,    8,    8,   36,    4,   29,   96,    3,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0],
         [   2,   30,    4,    8,    8,   36,    4,   29,   45,   26,   50,   11,
            37,  292,   45,   26,   50,   11,   10,    3,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0],
         [   2,   30,    4,    8,    8,   36,    4,   29,   45

In [3]:
from source.models.pgnet import PointerNet
model = PointerNet(corpus.SRC.vocab_size, 300, 800, padding_idx=corpus.padding_idx)

D:\Anaconda3\envs\anlp\lib\site-packages\torch\nn\_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))


In [4]:
model(enc_inputs, dec_inputs)

{'logits': tensor([[[-11.2345,  -5.2809, -11.1288,  ..., -11.2532, -11.2325, -11.1132],
          [-11.0839,  -5.5802, -10.9955,  ..., -11.0582, -11.0725, -11.1826],
          [-11.2291,  -5.4159, -11.2893,  ..., -11.6027, -11.3503, -11.1996],
          ...,
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093],
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093],
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093]],
 
         [[-11.1831,  -5.2835, -11.1463,  ..., -11.1879, -11.2059, -11.1529],
          [-11.6100,  -5.2872, -11.4595,  ..., -11.7079, -11.6138, -11.7082],
          [-11.3470,  -5.7157, -11.2809,  ..., -11.4788, -11.2415, -11.2571],
          ...,
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093],
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093],
          [-11.3849, -11.4216, -11.3843,  ..., -11.4085, -11.3796, -11.4093]],
 
         [[-11.225

In [5]:
outputs, dec_init_state = model.encode(enc_inputs, None)

In [6]:
dec_init_state.fact_mask[0]

tensor([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=torch.uint8)

In [7]:
dec_init_state.fact[0]

tensor([    4,    12,    11,     3,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     4,    22,
        26107,     3,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     4,    17,    28,    21,
          161,  7378,   355, 11000,     6,   153,  2381,   752,    39,     3,
            0,     0,     0,     0,     4,   104,   205,     3,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     8,    34,     1,   418,     7,  1252,     1,     3,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            8,    36,  7961,     3,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     8,   182,
          179,     3,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     8,    35, 

In [8]:
import torch

In [9]:
dec_inputs, _ = dec_inputs
input = dec_inputs[:, 0]

In [10]:
prob_vocab, p_mode, attn_f, attn_h, fact, hist = model.decoder.decode(input, dec_init_state)

In [11]:
weighted_prob = prob_vocab * p_mode[:, :, 0].unsqueeze(1)
weighted_f = attn_f * p_mode[:, :, 1].unsqueeze(1)
weighted_h = attn_h * p_mode[:, :, 2].unsqueeze(1)

In [12]:
from source.utils.misc import convert_dist

In [13]:
weighted_prob = convert_dist(
                weighted_h, hist, weighted_prob)

In [14]:
weighted_prob = convert_dist(
                weighted_f, fact, weighted_prob)

In [15]:
attn_f[0]

tensor([[0.0144, 0.0148, 0.0143, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0137, 0.0150, 0.0139, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0145, 0.0139, 0.0133, 0.0119, 0.0141, 0.0138, 0.0145, 0.0168, 0.0157,
         0.0137, 0.0134, 0.0155, 0.0136, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0147, 0.0162, 0.0146, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0127, 0.0149, 0.0148, 0.0152, 0.0148, 0.0152, 0.0148, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0130, 0.0157, 0.0180, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0123, 0.0129, 0.0

In [16]:
# out_facts, fact, hist, out_hists, prob_vocab, prob_hist, prob_fact, p_modes = model(enc_inputs, dec_inputs)

In [17]:
# model(enc_inputs, dec_inputs)

In [1]:
from source.inputters.corpus2 import HieraSrcCorpus
corpus = HieraSrcCorpus('./data/', 'hsrc', max_len=500, max_vocab_size=30000, share_vocab=True)
corpus.load()

valid_raw = corpus.read_data('./data/hsrc.dev', data_type='valid')
valid_data = corpus.build_examples(valid_raw)

from source.inputters.dataset import Dataset
data = Dataset(valid_data)
loader = data.create_batches(5)
for input in loader:
    input = input
    break

Loading prepared vocab from ./data/hsrc_30000.vocab.pt ...
Vocabulary size of fields: SRC-30004 TGT-30004 CUE-30004
Loading prepared data from ./data/hsrc_30000.data.pt ...
Number of examples: TRAIN-89901 VALID-9054 TEST-9054


100%|████████████████████████████████████████████████████████████████████████████| 9054/9054 [00:01<00:00, 8838.20it/s]


In [2]:
input.src

(tensor([[[   2,   29,    4,    8,    8,   35,    4,    3,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0],
          [   2,   95,    3,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0],
          [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0],
          [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0],
          [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
              0,    0,    0],
          [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
   

In [3]:
from source.modules.embedder import Embedder
from source.modules.encoders.rnn_encoder import RNNEncoder
from source.modules.encoders.rnn_encoder import HRNNEncoder

In [4]:
embedder = Embedder(num_embeddings=corpus.SRC.vocab_size,
                                embedding_dim=300,
                                padding_idx=corpus.padding_idx)
sub_encoder = RNNEncoder(input_size=300,
                          hidden_size=800,
                          embedder=embedder,
                          num_layers=1,
                          bidirectional=False,
                          dropout=0.0)
hiera_encoder = RNNEncoder(input_size=800,
                          hidden_size=800,
                          num_layers=1,
                          bidirectional=False,
                          dropout=0.0)

In [5]:
encoder = HRNNEncoder(sub_encoder, hiera_encoder)

In [6]:
indices, lengths = input.src
batch_size, max_hiera_len, max_sub_len = indices.size()
hiera_lengths = lengths.gt(0).long().sum(dim=1)

In [7]:
hiera_lengths

tensor([2, 3, 5, 7, 2])

In [10]:
hiera_outputs, hiera_hidden, _ = encoder(input.src)

In [11]:
hiera_outputs.size()

torch.Size([5, 7, 800])

In [12]:
hiera_hidden.size()

torch.Size([1, 5, 800])

In [2]:
from source.models.hseq2seq import HSeq2Seq
model = HSeq2Seq(corpus.SRC.vocab_size, corpus.SRC.vocab_size, 300, 800, padding_idx=corpus.padding_idx)

In [3]:
model.encode(input)

({}, <source.modules.decoders.state.DecoderState at 0x26bb5007c50>)

In [1]:
from source.inputters.tri_corpus import TriSrcCorpus
corpus = TriSrcCorpus('./data/', 'demo', max_len=500, max_vocab_size=30000, share_vocab=True)
corpus.load()
valid_raw = corpus.read_data('./data/demo.dev', data_type='valid')

Loading prepared vocab from ./data/demo_30000.vocab.pt ...
Vocabulary size of fields: SRC-30004 TGT-30004 CUE-30004
Loading prepared data from ./data/demo_30000.data.pt ...
Number of examples: TRAIN-89901 VALID-9054 TEST-9054


In [12]:
valid_raw[7]

{'src': 'START video_topic_a video_topic_b video_topic_a 类型 剧情 video_topic_b 类型 剧情 : 你 喜欢 看 美国 电影 吗 ？ 很喜欢 ， 你 这么 问 ， 你 也 喜欢 吗 ？ 我 也 喜欢 ， 那 你 看 过 Heather McComb 主演 的 video_topic_a 吗 ？ 是 2008年 上映 的 那 一部 吗 ？ 对 ， 2008年 3月2日 上映 的 。 挺 好看 的 。',
 'tgt': '还有 一部 电影 叫 video_topic_b ， 而且 还是 你 喜欢 的 战争 类型 的 影片 哦 ！',
 'cue': ['video_topic_a 是否 上映 已 上映',
  'video_topic_a 导演 Sarab Neelam',
  'video_topic_a 口碑 口碑 很 差',
  'video_topic_a 类型 剧情',
  'video_topic_a 领域 电影',
  'video_topic_b 类型 战争',
  'video_topic_b 时光网 短评 video_topic_b 已逝 ， 但求 无悔 … …',
  'video_topic_b 是否 上映 已 上映',
  'video_topic_b 领域 电影',
  'video_topic_a 国家 美国',
  'video_topic_a 主演 Heather McComb',
  'video_topic_a 上映 时间 2008年 3月2日'],
 'tag': [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]}

In [3]:
valid_data = corpus.build_examples(valid_raw)

100%|████████████████████████████████████████████████████████████████████████████| 9054/9054 [00:00<00:00, 9772.45it/s]


In [6]:
valid_data[0]

{'src': [2, 30, 4, 8, 8, 36, 4, 29, 96, 3],
 'tgt': [2, 45, 26, 50, 11, 37, 292, 3],
 'cue': [[2, 4, 12, 11, 3],
  [2, 4, 22, 26107, 3],
  [2, 4, 17, 28, 21, 161, 7378, 355, 11000, 6, 153, 2381, 752, 39, 3],
  [2, 4, 104, 205, 3],
  [2, 8, 34, 1, 418, 7, 1252, 1, 3],
  [2, 8, 36, 7961, 3],
  [2, 8, 182, 179, 3],
  [2, 8, 35, 58, 3],
  [2, 8, 32, 38, 3],
  [2, 8, 12, 23, 3],
  [2, 8, 66, 288, 3],
  [2,
   4,
   17,
   28,
   7378,
   11,
   6,
   100,
   1475,
   548,
   292,
   292,
   7,
   837,
   365,
   990,
   7,
   2273,
   10,
   3],
  [2, 4, 15, 50, 3]],
 'tag': [0, 0, 1, 1, 0, 1]}

In [8]:
corpus.SRC.itos[3]

'<eos>'